name: Add KiCad generated outputs to release
on:
  release:
    types: [published]

jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest

    steps:
    - uses: actions/checkout@v4  # GitHub built-in repo checkout step.
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        schema: "Hardware/BioCache.kicad_sch"

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          JLCPCB/*.zip
          Docs/*
        token: ${{ secrets.UPDATE_RELEASE_TOKEN }}
